### ISSUE TITLE
Policy Representation and Tracking

### ISSUE THREAD

**Issue by KinanBab** [brownsys/Sesame#3]
- [x] Custom Policy struct with Policy trait to check the access control policy for websubmit
- [x] Policy may refer to sibling data to what it is over (e.g. answer's policy depends on the student that submitted FK).
- [x] Policy should come / be set by the user. Our BBoxing proxy should handle getting the policy from the HTTP request and instantiating user-level policies (given user identity), and global policy (given data type / schema?). Proxy should apply for Forms, Get parameters, and Cookies.
- [ ] Policy should be stored/tracked when writing to DB, global policy can be rededuced without storage, user-level policy should only be stored once for the user. Row level policy should be serialized/deserialized.
